### PR TITLE
Normalize watched-path encoding

### PR DESCRIPTION
**Pull request by ashmaroli**
The crux of this proposal is to *normalize* the encoding of paths, with respect to that of the configured source directory (as against *forcing* all paths to `UTF-8`), to *restore* and improve handling of watching paths that contain accents and similar representations.

Resolves jekyll/jekyll#7083

(This PR also renames the test-directory to contain an accented character)

### CODE REVIEW

**Comment by javag97** [comment]
Thank you for writing this. I've had this issue on my Mac for a while, which led me to configure Jekyll on a different Windows computer.

**Comment by ashmaroli** [comment]
@javag97 You're welcome.

**Comment by javag97** [comment]
Oh darn. This issue is still giving me headaches even now. Can I gain write access somehow?

**Comment by ashmaroli** [comment]
@javag97 Sorry for the delay in addressing your inconvenience.
I'll update the branch

**Comment by parkr** [comment]
@jekyllbot: merge +bug

**Comment by DirtyF** [comment]
I just got an awkard error log with latest version while testing:

```sh
jekyll/tests/testé-saçésur
➜ bundle exec jekyll serve
Configuration file: /Users/frank/code/jekyll/tests/testé-saçésur/_config.yml
            Source: /Users/frank/code/jekyll/tests/testé-saçésur
       Destination: public
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.065 seconds.
 Auto-regeneration: enabled for '/Users/frank/code/jekyll/tests/testé-saçésur'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
[2018-10-10 00:15:20] ERROR `/favicon.ico' not found.
E, [2018-10-10T00:15:54.631418 #1537] ERROR -- : exception while processing events: "\xC3" from ASCII-8BIT to UTF-8 Backtrace:
 -- /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-watch-2.1.0/lib/jekyll/watcher.rb:69:in `encode!'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-watch-2.1.0/lib/jekyll/watcher.rb:69:in `block in normalize_encoding'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-watch-2.1.0/lib/jekyll/watcher.rb:69:in `map'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-watch-2.1.0/lib/jekyll/watcher.rb:69:in `normalize_encoding'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-watch-2.1.0/lib/jekyll/watcher.rb:57:in `block in listen_handler'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add
```

**Pull request merged**
