### PR TITLE
Remove unused declaration in gemspec

### PR DESCRIPTION
**Pull request by ashmaroli**
This PR removes the following lines because it has proven to be redundant as summarized in the subsequent bullet-points
```ruby
  require "rbconfig"
  if RbConfig::CONFIG["host_os"] =~ %r!mswin|mingw|cygwin!
    spec.add_runtime_dependency "wdm", "~> 0.1.0"
  end
```

- `gem 'wdm'` does not get installed on any of the Windows machines automatically like `runtime_dependencies` usually do. Evidenced by:
  - AppVeyor logs for `script/default-site` from `jekyll/jekyll`. [[Sample Log](https://ci.appveyor.com/project/jekyll/jekyll/build/2304/job/y8soeycr52us6pl2#L130)]
  - Multiple issues at jekyll/jekyll repo that mention a warning from `Listen` advising Windows user to include `gem 'wdm'` in their Gemfile.
This wouldn't occur if `gem 'wdm'` was a runtime dependency.
- Including that code makes sense if a `jekyll-watch` gem was being built specifically for Windows. But that is not the current case and it is unnecessary, as `jekyll-watch` runs fine on Windows in current form.

### CODE REVIEW

**Comment by ashmaroli** [comment]
The code seems to come into play only when a gem is built on a Windows OS..

The ***installed specification file*** for `jekyll-watch-1.5.0.gem`:
```ruby
# -*- encoding: utf-8 -*-
# stub: jekyll-watch 1.5.0 ruby lib

Gem::Specification.new do |s|
  s.name = "jekyll-watch".freeze
  s.version = "1.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Parker Moore".freeze]
  s.date = "2016-07-20"
  s.email = ["parkrmoore@gmail.com".freeze]
  s.homepage = "https://github.com/jekyll/jekyll-watch".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.13".freeze
  s.summary = "Rebuild your Jekyll site when a file changes with the `--watch` switch.".freeze

  s.installed_by_version = "2.6.13" if s.respond_to? :installed_by_version

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<listen>.freeze, ["< 3.1", "~> 3.0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.6"])
      s.add_development_dependency(%q<rubocop>.freeze, ["~> 0.35.1"])
      s.add_development_dependency(%q<rake>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.0"])
      s.add_development_dependency(%q<jekyll>.freeze, [">= 2.0"])
    else
      s.add_dependency(%q<listen>.freeze, ["< 3.1", "~> 3.0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.6"])
      s.add_dependency(%q<rubocop>.freeze, ["~> 0.35.1"])
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.0"])
      s.add_dependency(%q<jekyll>.freeze, [">= 2.0"])
    end
  else
    s.add_dependency(%q<listen>.freeze, ["< 3.1", "~> 3.0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.6"])
    s.add_dependency(%q<rubocop>.freeze, ["~> 0.35.1"])
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.0"])
    s.add_dependency(%q<jekyll>.freeze, [">= 2.0"])
  end
end
```
The ***installed specification file*** for a dummy `jekyll-watch-1.6.0.gem` which I just built on my Windows machine off current `master`:
```ruby
# -*- encoding: utf-8 -*-
# stub: jekyll-watch 1.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = "jekyll-watch".freeze
  s.version = "1.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Parker Moore".freeze]
  s.date = "2017-10-31"
  s.email = ["parkrmoore@gmail.com".freeze]
  s.homepage = "https://github.com/jekyll/jekyll-watch".freeze
  s.licenses = ["MIT".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.1.0".freeze)
  s.rubygems_version = "2.6.13".freeze
  s.summary = "Rebuild your Jekyll site when a file changes with the `--watch` switch.".freeze

  s.installed_by_version = "2.6.13" if s.respond_to? :installed_by_version

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<listen>.freeze, ["~> 3.0"])
      s.add_runtime_dependency(%q<wdm>.freeze, ["~> 0.1.0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.15"])
      s.add_development_dependency(%q<jekyll>.freeze, ["~> 3.6"])
      s.add_development_dependency(%q<rake>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.0"])
      s.add_development_dependency(%q<rubocop>.freeze, ["~> 0.5"])
    else
      s.add_dependency(%q<listen>.freeze, ["~> 3.0"])
      s.add_dependency(%q<wdm>.freeze, ["~> 0.1.0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.15"])
      s.add_dependency(%q<jekyll>.freeze, ["~> 3.6"])
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.0"])
      s.add_dependency(%q<rubocop>.freeze, ["~> 0.5"])
    end
  else
    s.add_dependency(%q<listen>.freeze, ["~> 3.0"])
    s.add_dependency(%q<wdm>.freeze, ["~> 0.1.0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.15"])
    s.add_dependency(%q<jekyll>.freeze, ["~> 3.6"])
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.0"])
    s.add_dependency(%q<rubocop>.freeze, ["~> 0.5"])
  end
end
```

**Comment by pathawks** [comment]
Maybe we should build two different versions of the :gem:Gem?

One could have `platform` set for Windows and include `wdm`.

**Comment by pathawks** [comment]
This is kind of beyond my Ruby Gems knowledge. Is it possible to upload multiple platforms for a particular version of a Gem? How does all that work?

If it _is_ possible, it would be easy to automate with the release script.

**Comment by ashmaroli** [comment]
> Maybe we should build two different versions of the Gem?

Like I mentioned, its not necessary at all.. since `jekyll-watch` works as intended (to my knowledge) on Windows..

**Comment by pathawks** [comment]
@ashmaroli But Windows users get a warning that they need to install `wdm`?

**Comment by ashmaroli** [comment]
> Is it possible to upload multiple platforms for a particular version of a Gem?

Yes, [Nokogiri](https://rubygems.org/gems/nokogiri) does it all the time..

**Comment by ashmaroli** [comment]
> But Windows users get a warning that they need to install wdm?

Yes they do.. (i'm a Windows user)
But my `Gemfile.lock` doesn't include `wdm` and everything works fine.. I had raised an issue at guard/listen.. but received no response..

**Comment by pathawks** [comment]
_Or_ the release script could just modify the generated `.gem` file to add the missing logic.

**Comment by pathawks** [comment]
Users should receive warnings if we can help it. Otherwise, we see all sorts of support issues that nobody has any good answers for.

**Comment by ashmaroli** [comment]
Prior discussion at jekyll/jekyll: https://github.com/jekyll/jekyll/issues/5581

**Comment by XhmikosR** [comment]
We have AppVeyor so why not rebase? You guys should enable the option for the branches to be always up to date.

**Comment by XhmikosR** [comment]
I think it's not required, at least I haven't even installed wdm for years.

**Comment by ashmaroli** [comment]
@XhmikosR Actually, it is necessary for a performance boost on Windows..
I have experienced it first-hand

`jekyll new ..` [adds that to `Gemfile`](https://github.com/jekyll/jekyll/blob/fd6e01fd6a33365deaf19832f25f1b77e1d93697/lib/jekyll/commands/new.rb#L93-L94) for that reason.

**Comment by XhmikosR** [comment]
Ah, true, forgot about that.

**Comment by XhmikosR** [comment]
Although to be honest, the whole experience is very slow for me anyway.

**Pull request closed without merging**
