### PR TITLE
Drop support for old Ruby and old Jekyll

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Drop support for old Ruby and old Jekyll
```

### CODE REVIEW

**Comment by ashmaroli** [comment]
Jekyll dropped support for `Ruby 2.0.x` because its dependency `Liquid` dropped support for `Ruby 2.0`, Now another dependency (this plugin) is going to force Jekyll to drop support for `Ruby 2.1` as well...
In about 5months, `Ruby 2.2` will become EOL as well.. perhaps some other dependency may drop support for `Ruby 2.2` which would force Jekyll to yield again..

Sad..

**Comment by pathawks** [comment]
I guess we don't _have_ to drop support for Ruby 2.1, but it _is_ EOL so it seems like everybody _should_ drop support.

**Comment by pathawks** [comment]
@ashmaroli You do raise a good point though. Because this plugin is **required** by Jekyll, it's requirements should be no more strict than Jekyll's requirements.

**Comment by ashmaroli** [comment]
> I guess we don't have to drop support for Ruby 2.1

As a matter of fact, you have little choice here now because `listen 3.1` has dropped support for `Ruby 2.1`

**Comment by pathawks** [comment]
> As a matter of fact, you have little choice here now because listen 3.1 has dropped support for Ruby 2.1

Do we _need_ `listen 3.1`? We don't require it.

**Comment by ashmaroli** [comment]
> We don't require it.

Ah right.. my bad.. I assumed #50 would cause one to depend on Listen 3.1..
We're safe then..

**Comment by pathawks** [comment]
It _allows_ a later version of Listen, but locking to `listen 3.0` still works.

**Comment by DirtyF** [comment]
@jekyllbot: merge +dev

**Comment by ashmaroli** [comment]
@DirtyF I believe this wasn't ready for a merge..
we can't have `jekyll-watch` drop support for Ruby 2.1 which Jekyll still supports..

**Comment by DirtyF** [comment]
`listen` is right we should also drop support for Ruby 2.1 it's EOL.

**Comment by DirtyF** [comment]
amended in https://github.com/jekyll/jekyll-watch/commit/b1dd7e7e246f127422b6451f762dd6df34d04cab and opened https://github.com/jekyll/jekyll/issues/6503

**Pull request merged**
