### PR TITLE
Fix encoding discrepancy in excluded Windows paths

### PR DESCRIPTION
**Pull request by ashmaroli**
## Summary
When a site is in a directory containing characters with accents and similar entities (e.g., `testé-çasésûr`),
the paths were encoded differently which were seen as a separate directory in the site.

## Context

https://github.com/jekyll/jekyll-watch/blob/adc010795c4f5536b3e6961954a68ea8d41a5de4/lib/jekyll/watcher.rb#L95-L105

If I were to have a custom destination set to "public", then the `absolute_path` in the code above gets created with encoding `Encoding:UTF-8` while the `options["source"]` encoding was in
`Encoding:Windows-1252`.
This resulted in a "relative_path" (via Pathname) starting with `../` which caused **that path to not be included as an ignored_path**
```
#<Pathname:D:/testAc-A§asAcsA»r/public>
#<Pathname:../testAc-A§asAcsA»r/public>
```
or when stringified:
```
D:/testAc-A§asAcsA»r/public
../testAc-A§asAcsA»r/public
```

### Steps to reproduce issue (Windows only)
- Create a site with accents in the path: `jekyll new testé-çasésûr`
- Add a custom `destination` configuration (regular string)
    ```yaml
    destination: public
    ```
- Watch the site: `bundle exec jekyll b --watch` or `bundle exec jekyll s`
- Make a change in any file..

/cc @jekyll/windows 

## Thanks

To @DirtyF for providing a test repository that led to the discovery of this bug

### CODE REVIEW

**Comment by XhmikosR** [comment]
Shouldn't there be a test case for this?

**Comment by XhmikosR** [comment]
Oh, wait, there is. Then we should have AppVeyor set up so that this doesn't happen again.

**Comment by ashmaroli** [comment]
@XhmikosR Do you want to add the `appveyor.yml`..? AppVeyor has been enabled on this repo..

**Comment by XhmikosR** [comment]
I could give it a go later, but my guess is you'd handle this faster than me :P

**Comment by DirtyF** [comment]
@jekyllbot: merge +fix

**Comment by ashmaroli** [comment]
@DirtyF Before this gets shipped, we need to ensure that this does not lead to any regressions in the encoding issues patched in the current public release..

**Pull request merged**
