### PR TITLE
Output regenerated file paths to terminal

### PR DESCRIPTION
**Pull request by ashmaroli**
With this, the plugin outputs the full path(s) of the regenerated files, in addition to the existing total count of regenerated files

### CODE REVIEW

**Comment by DirtyF** [comment]
current output:
```sh
      Regenerating: 1 file(s) changed at 2017-10-24 11:19:46
                    /Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site/css/main.scss
                    ...done in 0.116786 seconds.
```

@ashmaroli could we only display the relative path to the source directory like we already do for error messages?

```sh
[2017-10-24 11:22:16] ERROR `/favicon.ico' not found.
```

**Comment by ashmaroli** [comment]
> could we only display the relative path to the source directory

That's a good idea.. cleaner output, definitely. 
But, I opted for the full-path in sync with how the paths for `config-file`, `source` and `destination` were output..
```
Configuration file: /Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site/_config.yml
            Source: /Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site
       Destination: /Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.914 seconds.
 Auto-regeneration: enabled for '/Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2017-10-24 11:19:46
                    /Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site/css/main.scss
                    ...done in 0.116786 seconds.
```

But that said, I like the relative_path idea more..

---

Instead of wrapping the path in single-quotes, *may I* embellish with a padded-asterix?

```
Configuration file: /Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site/_config.yml
            Source: /Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site
       Destination: /Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.914 seconds.
 Auto-regeneration: enabled for '/Users/frank/code/jekyll/plugins/jekyll-watch/spec/test-site'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 3 file(s) changed at 2017-10-24 14:19:46
                     * /about.md
                     * /index.md
                     * /css/main.scss
                    ...done in 0.216786 seconds.
```

**Comment by DirtyF** [comment]
> Instead of wrapping the path in single-quotes, may I embellish with a padded-asterix?

We're not in Markdown but in console mode, asterix has a different meaning and adds confusion here.

As for the single-quotes,  I was just trying to be coherent but maybe we don't need them at all, we don't add anything in the profile option.

```
Configuration file: _config.yml
Configuration file: _config_local.yml
....
Filename                                                                            | Count |   Bytes |  Time
------------------------------------------------------------------------------------+-------+---------+------
feed.xml                                                                            |     1 | 220.19K | 2.217
sitemap.xml                                                                         |     1 |   3.15K | 1.146

```

Let's just go plain and simple. We can deal with style output in a different PR like we discussed before for colors.

**Comment by DirtyF** [comment]
```sh
      Regenerating: 1 file(s) changed at 2017-10-24 13:48:00
                    /_posts/2014-08-08-welcome-to-jekyll.markdown
                    ...done in 0.181475 seconds.
```

🙌 @ashmaroli

**Comment by mattr-** [comment]
If we're going to print the source dir relative paths for each file regenerated, let's remove the ellipsis as well.

**Comment by DirtyF** [comment]
We could go even more compact:

```
Regenerating: 3 file(s) changed at 2017-10-24 13:48:00
                    /_posts/2017-10-08-welcome-to-jekyll.markdown (0.181475 seconds)
                    /_posts/2016-09-07-another-post.markdown (0.201475 seconds)
                    /_posts/2015-08-06-really-lont-article.markdown (0.181475 seconds)
```

**Comment by mattr-** [comment]
Yup, could definitely do that. My preference is the summary line at the end but I'll let somebody else decide. :joy:

**Comment by parkr** [comment]
What does the output Look Like, when you have the `—verbose` flag set? `jekyll serve —verbose`

**Comment by DirtyF** [comment]
currently:

```sh
...
 Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2017-10-24 16:51:57
                    /_posts/2014-08-08-welcome-to-jekyll.markdown
           Reading: _posts/2014-08-08-welcome-to-jekyll copie 5.markdown
           Reading: _posts/2014-08-08-welcome-to-jekyll copie 4.markdown
           Reading: _posts/2014-08-08-welcome-to-jekyll.markdown
           Reading: _posts/2014-08-08-welcome-to-jekyll copie 2.markdown
           Reading: _posts/2014-08-08-welcome-to-jekyll copie 3.markdown
           Reading: _posts/2014-08-08-welcome-to-jekyll copie.markdown
         Rendering: _posts/2014-08-08-welcome-to-jekyll copie 2.markdown
  Pre-Render Hooks: _posts/2014-08-08-welcome-to-jekyll copie 2.markdown
  Rendering Liquid: _posts/2014-08-08-welcome-to-jekyll copie 2.markdown
         Requiring: rouge
...
```

**Comment by ashmaroli** [comment]
> let's remove the ellipsis as well

I kinda liked seeing the ellipsis.. sorta like *"...and cut! Its a wrap, folks!"* No..? 

> We could go even more compact

Honestly, I don't know how the suggested example can be implemented, given that we've an Array of path strings.. so leaving that for a future PR.. 

> What does the output look like, when you have the `--verbose` flag set?

The messages are logged at `level: info`, so its pretty much the same as illustrated in Frank's code blocks. So, @parkr, do you want me to drop the trailing `/` ?

**Comment by DirtyF** [comment]
> do you want me to drop the trailing `/` ?

```sh
Regenerating: 1 file(s) changed at 2017-10-24 16:51:57
                          _posts/2014-08-08-welcome-to-jekyll.markdown
           Reading: _posts/2014-08-08-welcome-to-jekyll.markdown
```
It would certainly look more coherent.

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
